---
lib_name: lib_spdif
project: '{{lib_name}}'
title: '{{lib_name}}: XMOS SPDIF Library'
version: 6.2.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/lib_spdif.rst
  linkcheck_ignore_regex: ['']
  cognidox_part_number: XM-006988-UG
  doxygen_projects:
    lib_spdif:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_spdif.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-007501-SM
